language: ruby
rvm:
  - rbx-2.1.1
  - rbx-2.1.0
  - rbx-2.0.0
  - 2.0.0
  - ruby-head
env:
  - COVERALLS=true
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2.0.0
    - rvm: rbx-2.1.0
    - rvm: rbx-2.1.1
script: bundle exec rake
