language: ruby
rvm:
  - rbx-2.1.1
  - 2.0.0
  - ruby-head
  - rbx-head
env:
  - COVERALLS=true
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-head
script: bundle exec rspec spec && bundle exec cucumber
